server:
  port: 8090
spring:
  datasource:
    name: dataSource
    url: jdbc:mysql://47.88.25.201:3306/zeros_wechat?serverTimezone=UTC&characterEncoding=utf8&useSSL=false
    username: test
    password: smart123
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      test-on-return: false
      test-on-borrow: false
      test-while-idle: true
      validation-query: select 'x'
      min-evictable-idle-time-millis: 300000
      time-between-eviction-runs-millis: 60000
      min-idle: 1
      max-wait-millis: 60000
      initial-size: 1
#    filters: stat
#    maxActive: 20
#    initialSize: 1
#    maxWait: 60000
#    minIdle: 1
#    timeBetweenEvictionRunsMillis: 60000
#    minEvictableIdleTimeMillis: 300000
#    validationQuery: select 'x'
#    testWhileIdle: true
#    testOnBorrow: false
#    testOnReturn: false
#    poolPreparedStatements: true
#    maxOpenPreparedStatements: 20
#mybatis:
#  type-aliases-package: com.zerostech.wechat.dao
#  mapper-locations: classpath:com/zerostech/wechat/dao/*.xml

