server:
  port: 8090
spring:
  datasource:
    name: dataSource
    url: jdbc:mysql://localhost:3306/smart?serverTimezone=UTC
    username: root
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

#mybatis:
#  type-aliases-package: com.zerostech.wechat.dao
#  mapper-locations: classpath:com/zerostech/wechat/dao/*.xml

